name: Compile PDFs

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v7

    - name: Compile
      run: make cv
    
    - name: Compile
      run: make coverletter

    - uses: actions/upload-artifact@v6
      with:
        name: personal
        path: ./*.pdf
